name: Merge feature into main branch
on:
  push:
    branches:
      - 'feature'
jobs:
  merge_feature:
    name: Merge feature into main branch
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[Bot]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Reset feature branch
        run: |
          export MAIN_VERSION="$(cat VERSION)"
          echo "Version of the main branch is ${MAIN_VERSION}"
          git fetch origin feature:feature
          git reset --hard feature
          echo "${MAIN_VERSION}" | tee VERSION
      - name: Generate token
        uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Submit pull request
        id: pr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: "[Bot] Merge feature into main branch."
          branch: merge-feature
          title: "Merge feature into main branch"
          labels: bot
          body: "Merge branch \"feature\" into \"main\"."
      - name: Enable auto-merge
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: gh pr merge --merge --auto "${{ steps.pr.outputs.pull-request-number }}"
