name: Merge feature into main branch
on:
  push:
    branches:
      - 'feature'
jobs:
  merge_feature:
    name: Merge feature into main branch
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[Bot]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Reset feature branch
        run: |
          git fetch origin feature:feature
          git reset --hard feature
      - name: Create pull request
        id: pr
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "[Bot] Merge feature into main branch."
          branch: merge-feature
          title: "[Bot] Merge feature into main branch"
          labels: bot
          body: "Merge branch \"feature\" into \"main\"."
      - name: Enable auto-merge
        run: gh pr merge --merge --auto "${{ steps.pr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ secrets.PAT }}
