name: Merge bugfix into feature branch
on:
  push:
    branches:
      - 'bugfix'
jobs:
  merge_bugfix:
    name: Merge bugfix into feature branch
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[Bot]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: feature
      - name: Reset bugfix branch
        run: |
          export FEATURE_VERSION="$(cat VERSION)"
          git fetch origin bugfix:bugfix
          git reset --hard bugfix
          echo $FEATURE_VERSION > VERSION
      - name: Create pull request
        id: pr
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "[Bot] Merge bugfix into feature branch."
          branch: merge-bugfix
          title: "Merge bugfix into feature branch"
          labels: bot
          body: "Merge branch \"bugfix\" into \"feature\"."
      - name: Enable auto-merge
        env:
          GH_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        run: gh pr merge --merge --auto "${{ steps.pr.outputs.pull-request-number }}"
