name: Merge release version
on:
  release:
    types: [ published ]
jobs:
  merge_release_version:
    name: Merge release version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup git
        uses: fregante/setup-git-user@v2
      - name: Checkout release branch
        run: |
          git checkout ${{ github.event.release.target_commitish }}
      - name: Drop development version
        continue-on-error: true
        run: |
          python -c "import update_version; update_version.drop_development_version()"
          git add VERSION
          git commit -m "[Bot] Updated version to $(cat VERSION)."
          git push origin ${{ github.event.release.target_commitish }}
      - name: Merge into feature branch
        if: ${{ github.event.release.target_commitish == 'main' }}
        run: |
          git checkout -b feature origin/feature
          git merge origin/main --no-edit --strategy-option theirs
          git push origin feature
      - name: Merge into bugfix branch
        if: ${{ github.event.release.target_commitish == 'main' }} || ${{ github.event.release.target_commitish == 'feature' }}
        run: |
          git checkout -b bugfix origin/bugfix
          git merge origin/feature --no-edit --strategy-option theirs
          git push origin bugfix
