name: Merge release version
on:
  release:
    types: [ published ]
jobs:
  merge_release_version:
    name: Merge release version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup git
        uses: fregante/setup-git-user@v2
      - name: Drop development version
        run: |
          python -c "import update_version; update_version.drop_development_version()"
          git add VERSION
          git commit -m "[Bot] Updated version to $(cat VERSION)."
          git push ${{ github.event.release.target_commitish }}
