name: Merge release version
on:
  release:
    types: [ published ]
jobs:
  merge_release_version:
    name: Merge release version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
      - name: Drop development version
        run: python -c "import update_version; update_version.drop_development_version()"
      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'VERSION'
          message: '[Bot] Drop development version.'
      - name: Merge into feature branch
        run: |
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
          git checkout main
          git checkout feature
          git merge main --no-edit --strategy-option theirs
          git push
      - name: Merge into feature branch
        run: |
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
          git checkout feature
          git checkout bugfix
          git merge feature --no-edit --strategy-option theirs
          git push
