name: Merge release version
on:
  release:
    types: [ published ]
jobs:
  merge_release_version:
    name: Merge release version
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate-token.outputs.token }}
      - name: Setup git
        uses: fregante/setup-git-user@v2
      - name: Checkout release branch
        run: |
          git checkout ${{ github.event.release.target_commitish }}
      - name: Merge into feature branch
        if: ${{ github.event.release.target_commitish == 'main' }}
        run: |
          git checkout -b feature origin/feature
          git merge origin/main --strategy-option theirs -m "[Bot] Merge branch \"main\" into \"feature\"."
          git push origin feature
      - name: Merge into bugfix branch
        if: ${{ github.event.release.target_commitish == 'main' }} || ${{ github.event.release.target_commitish == 'feature' }}
        run: |
          git checkout -b bugfix origin/bugfix
          git merge origin/feature --strategy-option theirs -m "[Bot] Merge branch \"feature\" into \"bugfix\"."
          git push origin bugfix
      - name: Update major version
        if: ${{ github.event.release.target_commitish == 'main' }}
        run: |
          git checkout main
          python -c "import update_version; update_version.increment_major_version()"
          git add VERSION
          git commit -m "[Bot] Update version to $(cat VERSION)."
          git push origin main
          git checkout feature
          python -c "import update_version; update_version.increment_minor_version()"
          git add VERSION
          git commit -m "[Bot] Update version to $(cat VERSION)."
          git push origin feature
          git checkout bugfix
          python -c "import update_version; update_version.increment_patch_version()"
          git add VERSION
          git commit -m "[Bot] Update version to $(cat VERSION)."
          git push origin bugfix
      - name: Update minor version
        if: ${{ github.event.release.target_commitish == 'feature' }}
        run: |
          git checkout feature
          python -c "import update_version; update_version.increment_minor_version()"
          git add VERSION
          git commit -m "[Bot] Update version to $(cat VERSION)."
          git push origin feature
          git checkout bugfix
          python -c "import update_version; update_version.increment_patch_version()"
          git add VERSION
          git commit -m "[Bot] Update version to $(cat VERSION)."
          git push origin bugfix
      - name: Update patch version
        if: ${{ github.event.release.target_commitish == 'bugfix' }}
        run: |
          git checkout bugfix
          python -c "import update_version; update_version.increment_patch_version()"
          git add VERSION
          git commit -m "[Bot] Update version to $(cat VERSION)."
          git push origin bugfix
