---
name: Create release
on:
  workflow_call:
    inputs:
      release_branch:
        required: true
        type: string
      release_version:
        required: true
        type: string
      changelog:
        required: true
        type: string
    secrets:
      app_id:
        required: true
      app_private_key:
        required: true
jobs:
  create_release:
    name: Create Github release
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ secrets.app_id }}
          private-key: ${{ secrets.app_private_key }}
      - name: Create Github release
        uses: softprops/action-gh-release@v2
        with:
          target_commitish: ${{ inputs.release_branch }}
          name: Version ${{ inputs.release_version }}
          tag_name: ${{ inputs.release_version }}
          body: ${{ inputs.changelog }}
          make_latest: true
          token: ${{ steps.generate-token.outputs.token }}
