---
name: Update changelog
on:
  workflow_call:
    inputs:
      release_branch:
        required: true
        type: string
    secrets:
      app_id:
        required: true
      app_private_key:
        required: true
    outputs:
      release_version:
        value: ${{ jobs.update_changelog.outputs.release_version }}
      latest_changelog:
        value: ${{ jobs.update_changelog.outputs.latest_changelog }}
jobs:
  update_changelog:
    name: Update changelog
    runs-on: ubuntu-latest
    outputs:
      release_version: ${{ steps.print_version.outputs.version }}
      latest_changelog: ${{ steps.print_latest_changelog.outputs.changelog }}
    steps:
      - name: Generate token
        uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ secrets.app_id }}
          private-key: ${{ secrets.app_private_key }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate-token.outputs.token }}
          ref: ${{ inputs.release_branch }}
      - name: Setup git
        uses: fregante/setup-git-user@v2
      - name: Update changelog
        run: |
          python -c "import changelog; changelog.update_changelog_${{ inputs.release_branch }}()"
          git add .changelog-*.md
          git add CHANGELOG.md
          git commit -m "[Bot] Update changelog."
          git push
      - id: print_version
        run: echo "version=$(python -c "import update_version; update_version.print_current_version()")" >> $GITHUB_OUTPUT
      - id: print_latest_changelog
        run: echo "changelog=$(python -c "import changelog; changelog.print_latest_changelog()")" >> $GITHUB_OUTPUT
